---

- hosts: uat
  become: yes
  vars:
   doc_root: "/var/www/html"
  
  tasks:
  - name: Install Apache Packages on Ubuntu
    apt: name=apache2 state=present
    when: ansible_os_family=="Debian"  

  - name: Install Apache Packages on CentOS
    yum: name=httpd state=present
    when: ansible_os_family=="RedHat"  

  - name: Copy abc.txt File to Destination
    copy: src=templates/abc.txt dest=/var/www/html/index.html
  
  - name: Copy info.j2 File to Destination
    template: src=templates/info.j2 dest=/var/www/html/info.html
  
  - name: Start Apache Service on Ubuntu
    service: name=apache2 state=started
    when: ansible_os_family=="Debian"

  - name: Start Apache Service on CentOS
    service: name=httpd state=started
    when: ansible_os_family=="RedHat"
